# Database connection details
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/aviation_air_report?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=airreport

# Hikari connection pooling
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=50
spring.datasource.hikari.idleTimeout=30000

# Aviation API URL
aviation_url=${AVIATION_API_URL:https://aviationweather.gov/api/data/dataserver}
