ALTER TABLE pirep ADD IF NOT EXISTS isIcingType BOOLEAN;

ALTER TABLE pirep ADD IF NOT EXISTS isSkyType BOOLEAN;

ALTER TABLE pirep ADD IF NOT EXISTS isTurbulenceType BOOLEAN;

ALTER TABLE pirep ADD IF NOT EXISTS isQualityControlFlagType BOOLEAN;