CREATE SEQUENCE  IF NOT EXISTS sky_condition_SEQ START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS sky_condition (
   id BIGINT NOT NULL DEFAULT nextval('sky_condition_SEQ') PRIMARY KEY,
   sky_cover VARCHAR(255),
   cloud_base_ft_agl INTEGER,
   cloud_top_ft_msl INTEGER,
   pirep_id BIGINT
);

ALTER TABLE sky_condition ADD CONSTRAINT FK_SKY_CONDITION_ON_PIREP FOREIGN KEY (pirep_id) REFERENCES pirep (id);